### ISSUE TITLE
79 errors

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/pro1formulieren#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/pimhakkert/pro1formulieren/blob/master/

Feedback: bij validatie[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Opdracht opnieuw gemaakt.
