### ISSUE TITLE
action en method ontbreken

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/pro1formulieren#2]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
</form> 
```

URL: https://github.com/pimhakkert/pro1formulieren/blob/master/index.html

Feedback: Zonder deze attributen wordt het formulier niet verwerkt.
En er is slechts 1 formulier met een submit-knop[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"3ae75b94b23ce4c960fced69f51440a753d957b5","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Opdracht opnieuw gemaakt.
