### ISSUE TITLE
gelijk aan boyd

### ISSUE THREAD

**Issue by Theo-denBlanken** [pimhakkert/pro1formulieren#5]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/pimhakkert/pro1formulieren/blob/master/index.html

Feedback: Dan leer je er niks van[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"3ae75b94b23ce4c960fced69f51440a753d957b5","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by pimhakkert** [comment]
Opdracht opnieuw gemaakt.
